### ISSUE TITLE
Consider using singleton produce method in TA1-2 api for metafeatures

### ISSUE THREAD

**Issue by bjschoenfeld** [byu-dml/d3m-primitives#17]

**Comment by mitar** [comment]
Hm, but if input is a `Dataset`, output should also be a `Dataset` with metadata updated, no? So `Dataset` input is already a container type, which can have more than one resource, so singleton output is probably not the best here?

**Comment by bjschoenfeld** [comment]
This should have been closed. It is as you said. The metafeature primitive updates the metadata and passes the input dataset through without modifying it, like an identity or no-op function.
