### ISSUE TITLE
Not possible to run primitives in non-main thread

### ISSUE THREAD

**Issue by mitar** [byu-dml/d3m-primitives#18]
I thought this was already reported somewhere. But because primitives use `signal` it is not possible to run them in non-main thread.

Not sure why you have a hard timeout anyway? The TA1-TA2 API is designed that `timeout` is soft timeout, you do not have to terminate exactly at that time. If TA2 wants to kill you from outside if you go over the timeout, they can, but then they can kill the thread/process and do stuff like that.

But primitive should use `timeout` to try to decide maybe on what to compute to be under the timeout, and then if there is a natural place to finish if they go over, can go over, and tell TA2 that they did have more to compute, but ended. (Or they can finish before, if primitive has good grasp how long another iteration will take and that it will go over.)

In the case of this primitive I would suggest you compute metafeatures in order from cheap to expensive or something like that and after each computation check if you are over the timeout, and if you are, you exist. But not need to kill anything internally if it happens that you get over.

**Comment by bjschoenfeld** [comment]
We found that the hard timeout was too difficult to implement well and it is currently removed from the [underlying package](https://github.com/byu-dml/metalearn/issues/110). Obviously this did not make it into the primitives repo before the freeze.

A soft timeout will be much easier to implement. We can default to computing the cheapest metafeatures first. Otherwise, we will compute the metafeatures in the order specified by the user, so they can control their preference.

A soft timeout has the disadvantage over a hard internal timeout that if the process takes too long to compute the next iteration, the process will be killed and nothing will be returned. However, seeing that we have not been successful with the hard timeout, a soft one will be much better than nothing.

**Comment by mitar** [comment]
> We can default to computing the cheapest metafeatures first. Otherwise, we will compute the metafeatures in the order specified by the user, so they can control their preference.

Hm, or maybe just list some cheap ones in the default value of the hyper-parameter. I think having the list dynamic based on provided timeout is tricky to reason about. So just pick some and put them as defaults, and then user can extend or modify or re-order the list.

> A soft timeout has the disadvantage over a hard internal timeout that if the process takes too long to compute the next iteration, the process will be killed and nothing will be returned.

So this is something TA2 can control. It can start with short list and then add additional ones if there is more time. I think this is also cleaner from the functional perspective: given the list of hyper-parameters, you get out those you requested. And not a random subset based on how long it took to compute on a particular machine.

Now that I think, I would even say that primitive should always compute all requested metafeatures. The timeout should maybe only apply if there are iterations inside computing the metafeatures (so for example how precisely are they computed). I could see that some metafeatures are computed by sampling, so sampling more or less can take then more or less time.

**Comment by bjschoenfeld** [comment]
> Hm, or maybe just list some cheap ones in the default value of the hyper-parameter.

This is actually the default now.

> I think this is also cleaner from the functional perspective: given the list of hyper-parameters, you get out those you requested. And not a random subset based on how long it took to compute on a particular machine.

> Now that I think, I would even say that primitive should always compute all requested metafeatures.

These are good points. I do not think we currently have any metafeatures that get more precision with time, like your sampling example or an iterative optimizer.
