### ISSUE TITLE
Handle Numeric Data Correctly

### ISSUE THREAD

**Issue by orionw** [byu-dml/d3m-primitives#28]
In calcuating MetaFeatures of many of the regression problems, we are finding that it does not handle numeric data correctly.   The base package is correctly returning NUMERIC_TARGETS but this package is trying to parse that as an int. 

We should fix that.

The following is the error message:

File "byudml/metafeature_extraction/metafeature_extraction.py", line 193, in _populate_metadata
    metafeature_val = int(metafeature_val)
ValueError: invalid literal for int() with base 10: 'NUMERIC_TARGETS'

**Comment by bjschoenfeld** [comment]
We need a test that uses a regression dataset.
