### ISSUE TITLE
Updating PyPI

### ISSUE THREAD

**Issue by remram44** [byu-dml/d3m-primitives#85]
Hi @bjschoenfeld, @epeters3!

We are trying to push the primitives to PyPI. We have been maintaining your primitives at [datadrivendiscovery/contrib/byu-d3m-primitives](https://gitlab.com/datadrivendiscovery/contrib/byu-d3m-primitives) and metalearn package at [datadrivendiscovery/contrib/metalearn](https://gitlab.com/datadrivendiscovery/contrib/metalearn), which has worked quite well for keeping the Docker images stable as we update D3M. However we don't have access to push updates to PyPI: [metalearn](https://pypi.org/project/metalearn/) and [byudml](https://pypi.org/project/byudml/) are registered under your accounts.

Would it be possible to release versions on PyPI with our changes, or give me access to do so? If you would rather not, I understand, and I will simply publish the forked version under different names.

Thanks,
-- Rémi

**Comment by epeters3** [comment]
Hey Remi, good to hear from you! I’m a little out of touch with the state
of those PyPi packages and who their current owners are. What do you think
of Remi’s proposal Brandon?

**Comment by bjschoenfeld** [comment]
Hi Remi! Thanks for maintaining these primitives. I have given you access to the github repos. If you give me your PyPI username, I can add you there as well.

**Comment by remram44** [comment]
Thanks Brandon! I am [`remram`](https://pypi.org/user/remram/) on PyPI.

**Comment by bjschoenfeld** [comment]
Done, thank you!
